# Storage Stack - VictoriaLogs + Prometheus
# Remote mode: Set STORAGE_BIND=0.0.0.0 to accept connections from collectors

services:
  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: sib-victorialogs
    restart: unless-stopped
    ports:
      - "${STORAGE_BIND:-127.0.0.1}:${VICTORIALOGS_PORT:-9428}:9428"
    command:
      - "-storageDataPath=/vlogs"
      - "-retentionPeriod=${VICTORIALOGS_RETENTION_PERIOD:-168h}"
    volumes:
      - victorialogs-data:/vlogs
    networks:
      - sib-network

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: sib-prometheus
    restart: unless-stopped
    ports:
      - "${STORAGE_BIND:-127.0.0.1}:${PROMETHEUS_PORT:-9090}:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-15d}'
      - '--storage.tsdb.retention.size=${PROMETHEUS_RETENTION_SIZE:-5GB}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - sib-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  sib-network:
    external: true

volumes:
  victorialogs-data:
  prometheus-data:
