#!/bin/bash
# Generate Falcosidekick configuration with optional mTLS settings
#
# Usage: ./scripts/generate-sidekick-config.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TEMPLATE="${PROJECT_ROOT}/alerting/config/config.yaml.template"
OUTPUT="${PROJECT_ROOT}/alerting/config/config.yaml"

# Load environment
MTLS_ENABLED="${MTLS_ENABLED:-false}"
STACK="${STACK:-vm}"

# Determine Loki endpoint based on stack
if [ "$STACK" = "vm" ]; then
    LOKI_HOSTPORT="http://sib-victorialogs:9428/insert"
else
    LOKI_HOSTPORT="http://sib-loki:3100"
fi

# Generate config
{
    echo "# Falcosidekick Configuration"
    echo "# Generated by generate-sidekick-config.sh"
    echo "# mTLS: ${MTLS_ENABLED}"
    echo "debug: false"
    echo ""
    echo "loki:"
    echo "  hostport: \"${LOKI_HOSTPORT}\""

    if [ "$MTLS_ENABLED" = "true" ]; then
        echo ""
        echo "# mTLS TLS Server Configuration"
        echo "tlsserver:"
        echo "  deploy: true"
        echo "  certfile: /certs/server/server.crt"
        echo "  keyfile: /certs/server/server.key"
        echo "  mutualtls: true"
        echo "  cacertfile: /certs/ca/ca.crt"
    fi
} > "$OUTPUT"

if [ "$MTLS_ENABLED" = "true" ]; then
    echo "Generated Falcosidekick config with mTLS enabled"
else
    echo "Generated Falcosidekick config (HTTP mode)"
fi
